spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

app:
  jwt:
    key: ${JWT_KEY}
  oauth:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
  github:
    token: ${GIT_TOKEN}
  admin:
    pw: ${ADMIN_PASSWORD}

logging:
  level:
    org.springframework.boot.autoconfigure: ERROR
