spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dgit?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: hong3622!
    #password: wlals0330
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

app:
  jwt:
    key: jwt_auth_secret_key_for_login_user
  oauth:
    client-id: 7f18bfb3af4b4983bbee44b13f08de58a37f3eae5a784a1e9a7e8f710f918f3d
    client-secret: 20b1d31d09214af790271a604c7070491e26a6d443d74af1b9d66c0b013fb160
  github:
    token: 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

logging:
  level:
    org.springframework.boot.autoconfigure: ERROR